/* Autogenerated by /.tools/auto.ts */

import key from "../rem.ts";
import value from "./methods/rem.ts";

declare global {
  interface Number {
    [key]: typeof value;
  }
}

Object.defineProperty(Number.prototype, key, { value });

