/* Autogenerated by /.tools/auto.ts */

import * as Generator from "../Generator.ts";

import key from "../slices.ts";
import value from "./methods/slices.ts";

declare global {
  interface Generator {
    [key]: typeof value;
  }
}

Object.defineProperty(Generator.prototype, key, { value });

