/* Autogenerated by /.tools/auto.ts */

export { default } from "./symbols/add.ts";

import "./WeakMap/add.ts";
import "./BigInt/add.ts";
import "./Array/add.ts";
import "./WeakSet/add.ts";
import "./Number/add.ts";
import "./Map/add.ts";
import "./Set/add.ts";
