/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./WeakMap/add.ts
 * @see ./BigInt/add.ts
 * @see ./Array/add.ts
 * @see ./WeakSet/add.ts
 * @see ./Number/add.ts
 * @see ./Map/add.ts
 * @see ./Set/add.ts
 */
const add = Symbol();

export default add;
