/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./SetConstructor/build.ts
 * @see ./StringConstructor/build.ts
 * @see ./MapConstructor/build.ts
 * @see ./ArrayConstructor/build.ts
 * @see ./WeakSetConstructor/build.ts
 * @see ./WeakMapConstructor/build.ts
 */
const build = Symbol();

export default build;
