/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./BigInt/compareTo.ts
 * @see ./Date/compareTo.ts
 * @see ./Number/compareTo.ts
 * @see ./Boolean/compareTo.ts
 * @see ./String/compareTo.ts
 */
const compareTo = Symbol();

export default compareTo;
