/* Autogenerated by /.tools/auto.ts */

export { default } from "./symbols/compareTo.ts";

import "./BigInt/compareTo.ts";
import "./Date/compareTo.ts";
import "./Number/compareTo.ts";
import "./Boolean/compareTo.ts";
import "./String/compareTo.ts";
