/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./SetConstructor/from.ts
 * @see ./MapConstructor/from.ts
 * @see ./WeakSetConstructor/from.ts
 * @see ./WeakMapConstructor/from.ts
 */
const from = Symbol();

export default from;
