/* Autogenerated by /.tools/auto.ts */

export { default } from "./symbols/from.ts";

import "./SetConstructor/from.ts";
import "./MapConstructor/from.ts";
import "./WeakSetConstructor/from.ts";
import "./WeakMapConstructor/from.ts";
