/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./SetConstructor/of.ts
 * @see ./MapConstructor/of.ts
 * @see ./WeakSetConstructor/of.ts
 * @see ./WeakMapConstructor/of.ts
 */
const of = Symbol();

export default of;
