/* Autogenerated by /.tools/auto.ts */

export { default } from "./symbols/of.ts";

import "./SetConstructor/of.ts";
import "./MapConstructor/of.ts";
import "./DequeConstructor/of.ts";
import "./WeakSetConstructor/of.ts";
import "./WeakMapConstructor/of.ts";
import "./QueueConstructor/of.ts";
