/* Autogenerated by /.tools/auto.ts */

export { default } from "./symbols/slices.ts";

import "./AsyncIterator/slices.ts";
import "./Array/slices.ts";
import "./Generator/slices.ts";
import "./Iterator/slices.ts";
