/* Autogenerated by /.tools/auto.ts */

/**
 * @see ./AsyncIterator/slices.ts
 * @see ./Array/slices.ts
 * @see ./Generator/slices.ts
 * @see ./Iterator/slices.ts
 */
const slices = Symbol();

export default slices;
