/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/pipe.ts";
import value from "./methods/pipe.ts";

declare global {
  interface Object {
    [key]: typeof value;
  }
}

Object.defineProperty(Object.prototype, key, { value });

export default key;
