/* Autogenerated by /.tools/auto.ts */

import TypedArray from "../TypedArray.ts";

import key from "../symbols/build.ts";
import value from "./methods/build.ts";

declare global {
  interface TypedArrayConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(TypedArray, key, { value });

export default key;
