/* Autogenerated by /.tools/auto.ts */

import key from "../build.ts";
import value from "./methods/build.ts";

declare global {
  interface StringConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(String, key, { value });

