/* Autogenerated by /.tools/auto.ts */

import Queue from "../Queue.ts";

import key from "../symbols/from.ts";
import value from "./methods/from.ts";

declare global {
  interface QueueConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(Queue, key, { value });

export default key;
