/* Autogenerated by /.tools/auto.ts */

import Deque from "../Deque.ts";

import key from "../symbols/add.ts";
import value from "./methods/add.ts";

declare module "../Deque.ts" {
  export default interface Deque<T> {
    [key]: typeof value;
  }
}

Object.defineProperty(Deque.prototype, key, { value });

export default key;
