/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/add.ts";
import value from "./methods/add.ts";

declare global {
  interface Set<T> {
    [key]: typeof value;
  }
  interface ReadonlySet<T> {
    [key]: typeof value;
  }
}

Object.defineProperty(Set.prototype, key, { value });

export default key;
