/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/build.ts";
import value from "./methods/build.ts";

declare global {
  interface WeakSetConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(WeakSet, key, { value });

export default key;
