/* Autogenerated by /.tools/auto.ts */

import key from "../of.ts";
import value from "./methods/of.ts";

declare global {
  interface WeakSetConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(WeakSet, key, { value });

