/* Autogenerated by /.tools/auto.ts */

import Queue from "../Queue.ts";

import key from "../symbols/add.ts";
import value from "./methods/add.ts";

declare module "../Queue.ts" {
  export default interface Queue<T> {
    [key]: typeof value;
  }
}

Object.defineProperty(Queue.prototype, key, { value });

export default key;
