/* Autogenerated by /.tools/auto.ts */

import key from "../add.ts";
import value from "./methods/add.ts";

declare global {
  interface Map<K, V> {
    [key]: typeof value;
  }
  interface ReadonlyMap<K, V> {
    [key]: typeof value;
  }
}

Object.defineProperty(Map.prototype, key, { value });

