/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/of.ts";
import value from "./methods/of.ts";

declare global {
  interface MapConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(Map, key, { value });

export default key;
