/* Autogenerated by /.tools/auto.ts */

import Deque from "../Deque.ts";

import key from "../symbols/from.ts";
import value from "./methods/from.ts";

declare global {
  interface DequeConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(Deque, key, { value });

export default key;
