/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/build.ts";
import value from "./methods/build.ts";

declare global {
  interface SetConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(Set, key, { value });

export default key;
