/* Autogenerated by /.tools/auto.ts */

import key from "../from.ts";
import value from "./methods/from.ts";

declare global {
  interface SetConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(Set, key, { value });

