/* Autogenerated by /.tools/auto.ts */

import key from "../symbols/from.ts";
import value from "./methods/from.ts";

declare global {
  interface WeakMapConstructor {
    [key]: typeof value;
  }
}

Object.defineProperty(WeakMap, key, { value });

export default key;
